source 'https://github.com/SSRComponent/SSRSpacs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SSRSpecialKit_Example' do
  pod 'SSRSpecialKit', :path => '../'

  target 'SSRSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
